server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 处理 SPA 路由，所有前端路由都返回 index.html
    location /admin {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /admin/index.html;
    }
}